#!/system/bin/sh

# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 Yumeka <miniyu157@163.com>

# shellcheck shell=ksh

(($(id -u) != 0)) && exec su -c "$(printf "%q " "$(readlink -f "$0")" "$@")"
ScriptDir=$(dirname "$0")
export LD_LIBRARY_PATH="/data/data/com.termux/files/usr/lib"
export PATH="/data/data/com.termux/files/usr/bin:$PATH"

# colorize
if [[ -t 1 ]] || [[ -n $FORCE_COLOR ]]; then
    COFF=$'\e[0m'
    BLUE=$'\e[34m'
fi
readonly COFF BLUE

command -v sqlcipher > /dev/null 2>&1 || {
    printf "找不到 sqlcipher, 在 Termux 中使用 'pkg install -y sqlcipher' 以安装。" >&2
    exit 1
}

USE_DISK=0
RAW=0

OUT_DIR="$ScriptDir/db_output"

while (($# > 0)); do
    case "$1" in
        --use-disk)
            USE_DISK=1
            shift
            ;;
        --raw)
            RAW=1
            shift
            ;;
        *)
            if [[ -d $1 ]]; then
                OUT_DIR="$1"
            else
                printf "不是文件夹: %s" "$1" >&2
                exit 1
            fi
            shift
            ;;
    esac
done

[[ ! -w "/tmp" ]] && USE_DISK=1

mkdir -p "$OUT_DIR"

if ((USE_DISK == 1)); then
    TMP_DIR="$ScriptDir/dumpdb.$$.tmp"
else
    TMP_DIR="/tmp/dumpdb.$$.tmp"
fi
mkdir -p "$TMP_DIR"
cleanup() {
    rm -rf "$TMP_DIR"
}
trap cleanup EXIT HUP INT QUIT TERM

TIMESPAN="$(date +%Y-%m-%d_%H-%M-%S)"

"$ScriptDir"/dumpkey --raw | while read -r QQPATH PATH_HASH QQ UID KEY; do
    _raw_user="${QQPATH#/data/user/}"
    user="${_raw_user%%/*}"
    target_dir="$OUT_DIR/$TIMESPAN/${user}_${QQ}"

    mkdir -p "$target_dir"
    _prefix="${ScriptDir}/"
    if ((RAW == 1)); then
        printf "%s\n" "${target_dir##"$_prefix"}"
    else
        printf "${BLUE}[%s] %s ==> %s${COFF}\n" "$user" "$QQ" "${target_dir##"$_prefix"}"
    fi

    for db_path in "$QQPATH/databases/nt_db/nt_qq_$PATH_HASH"/*.db; do
        [[ -e $db_path ]] || continue
        [[ $db_path == *"$UID.db" ]] && continue

        _db_name="${db_path##*/}"
        [[ -s "$ScriptDir/db_list.txt" ]] && {
            grep -qxF "$_db_name" "$ScriptDir/db_list.txt" || continue
        }

        ((RAW != 1)) && printf "  -> %s\n" "$_db_name"

        final_db="$target_dir/${_db_name%.*}.db"

        tmp_clean="$TMP_DIR/.tmp_${_db_name}"
        dd if="$db_path" of="$tmp_clean" bs=1024 skip=1 2> /dev/null

        rm -f "$final_db"
        {
            cat << EOF
PRAGMA key = '$KEY';
PRAGMA kdf_iter = 4000;
PRAGMA cipher_hmac_algorithm = HMAC_SHA1;
PRAGMA cipher_page_size = 4096;
ATTACH DATABASE '$final_db' AS plaintext KEY '';
SELECT sqlcipher_export('plaintext');
DETACH DATABASE plaintext;
EOF
        } | sqlcipher "$tmp_clean" > /dev/null 2>&1

        rm -f "$tmp_clean"
    done
done
