#!/system/bin/sh

# A minimalist, dependency-free QQ NT database key extractor for Android
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 Yumeka <miniyu157@163.com>

# shellcheck shell=ksh

(($(id -u) != 0)) && exec su -c "$(printf "%q " "$(readlink -f "$0")" "$@")"

# colorize
if [[ -t 1 ]] || [[ -n $FORCE_COLOR ]]; then
    COFF=$'\e[0m'
    RED=$'\e[31m'
fi
readonly COFF RED

files=(/data/user/*/com.tencent.mobileqq/files/uid/*)
last=$((${#files[@]} - 1))

for i in "${!files[@]}"; do
    UidFile=${files[$i]}
    [[ -e $UidFile ]] || continue

    QQPath="${UidFile%/files/uid/*}"

    _raw_name="${UidFile##*/}"
    qq="${_raw_name%%###*}"
    uid="${_raw_name##*###}"

    _raw_uid_hash=$(echo -n "$uid" | md5sum)
    uid_hash="${_raw_uid_hash%% *}"
    _raw_path_hash=$(echo -n "${uid_hash}nt_kernel" | md5sum)
    path_hash="${_raw_path_hash%% *}"
    rand=$(strings "$QQPath"/databases/nt_db/nt_qq_"$path_hash"/profile_info.db | grep -A 1 'QQ_NT DB' | tail -n 1 | grep -oE '[a-zA-Z0-9]{8}')

    raw_key=$(echo -n "$uid_hash$rand" | md5sum)
    key="${raw_key%% *}"

    case "$1" in
        --raw)
            printf "%s %s %s %s %s" "$QQPath" "$path_hash" "$qq" "$uid" "$key"
            ;;
        *)
            cat << EOF
${RED}QQPath:${COFF}     $QQPath
${RED}qq:${COFF}         $qq
${RED}uid:${COFF}        $uid
${RED}uid_hash:${COFF}   $uid_hash
${RED}path_hash:${COFF}  $path_hash
${RED}rand:${COFF}       $rand
${RED}key:${COFF}        $key
EOF

            ;;
    esac

    [[ $i != "$last" || $1 == "--raw" ]] && {
        printf "\n"
    }
done
