#!/system/bin/sh

# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2025 Yumeka <miniyu157@163.com>

# shellcheck shell=ksh

SelfRoot="$(dirname "$(readlink -f "$0")")"
GitBranch="$(git -C "$SelfRoot" rev-parse --abbrev-ref HEAD)"
SELF_VERSION="r$(git -C "$SelfRoot" rev-list --count HEAD)-$(git -C "$SelfRoot" rev-parse --short HEAD)"
Self="${0##*/}"

# colorize
if [[ -t 1 ]] || [[ -n $FORCE_COLOR ]]; then
    COFF=$'\e[0m'
    BOLD=$'\e[1m'

    GREEN=$'\e[32m'
    YELLOW=$'\e[33m'
    GRAY=$'\e[38;5;243m'
fi
readonly COFF BOLD GREEN YELLOW GRAY

[[ -f "$SelfRoot/.dev" ]] || {
    [[ -f "$SelfRoot/update.lock" ]] && {
        echo "$Self 上次启动时进行了更新, 更新内容是:"
        cat "$SelfRoot/update.lock"
        rm -f "$SelfRoot/update.lock"
        echo ""
    }
    (cd "$SelfRoot" && /system/bin/sh update > /dev/null 2>&1 &)
}

usage() {
    cat << EOF
$Self ${YELLOW}($GitBranch)${COFF} ${GRAY}$SELF_VERSION${COFF}

${BOLD}用法: $Self <指令> [参数...]${COFF}
${BOLD}指令:${COFF} key,k database,db chat

远程仓库: ${GREEN}https://github.com/miniyu157/qq-dump${COFF}
更多信息和说明请查看 README.md 文件
EOF

    exit "${1:-0}"
}

[[ -z $1 ]] && {
    usage 0
}

Command="$1"
shift

start_time=$(date +%s%3N)

case "$Command" in
    k | key)
        [[ -x "$SelfRoot/dumpkey" ]] || {
            printf "错误: 找不到 dumpkey" >&2
            exit 1
        }
        "$SelfRoot/dumpkey" "$@"
        ;;
    db | database)
        [[ -x "$SelfRoot/dumpdb" ]] || {
            printf "错误: 找不到 dumpdb" >&2
            exit 1
        }
        "$SelfRoot/dumpdb" "$@"
        ;;
    chat)
        [[ -x "$SelfRoot/dumpchat" ]] || {
            printf "错误: 找不到 dumpchat" >&2
            exit 1
        }
        "$SelfRoot/dumpchat" "$@"
        exit $?
        ;;
    *)
        printf "未知指令: %s, 输入 %s 以查看可用指令\n" "$Command" "$Self" >&2
        exit 1
        ;;
esac

duration=$(($(date +%s%3N) - start_time))

printf "\n"
printf "${BOLD}${GREEN}Total runtime:${COFF} %sms\n" "$duration"
